# Generated by Django 5.0.7 on 2024-07-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name': 'TaskStatus', 'verbose_name_plural': 'TaskStatuses'},
        ),
    ]
